// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheBerbakery.API.Models;

/// <summary>
/// Ingredients for a specific recipe
/// When a recipe is deleted, all recipe steps and ingredients associated with the deleted recipe are also deleted
/// </summary>
public partial class RecipeIngredients
{
    public int RecipeId { get; set; }

    public int IngredientId { get; set; }

    public string IngredientDescription { get; set; }

    public virtual Recipes Recipe { get; set; }
}