// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace TheBerbakery.API.Models;

/// <summary>
/// Ingredients for a specific recipe
/// When a recipe is deleted, all recipe steps and ingredients associated with the deleted recipe are also deleted
/// </summary>
public partial class RecipeIngredient
{
    public int RecipeId { get; set; }

    public int IngredientId { get; set; }

    public string IngredientDescription { get; set; }
    [JsonIgnore]
    public virtual Recipe Recipe { get; set; }
}